Caching changes
NeonGeckoCom/mall_guide_skill pull request #7
Opened 2022-09-27 17:56 UTC by NeonMariia

2022-09-27 18:08 UTC, NeonDaniel requested changes
.github directory should be replaced and __pycache__ directory removed. Otherwise changes look good

2022-09-27 18:08 UTC, NeonDaniel commented on __init__.py
> +        if message.data == {} or message is None:
Consider annotating the return params in a docstring

2022-09-27 18:08 UTC, NeonDaniel commented on __init__.py
> +        # change to speak dialog
Is this a TODO or just leftover comment? The docstring is good, so I think these lines can be removed

2022-09-27 18:08 UTC, NeonDaniel commented on __init__.py
> +            normalized_time = re.findall(r'(\d+)[am|pm]', work_time)
Just a note that using `datetime` might simplify things in the future; the parsing here looks good though

2022-09-27 21:27 UTC, NeonDaniel commented
Is this related to https://github.com/NeonGeckoCom/skill-directory/pull/6 ?

2022-09-29 09:01 UTC, NeonMariia commented
> Is this related to #6 ?

Yes, still related and can be merged I guess?

2022-09-29 16:44 UTC, NeonDaniel approved these changes

2022-09-29 16:46 UTC, NeonDaniel commented
> > Is this related to #6 ?
> 
> Yes, still related and can be merged I guess?

Is this a replacement? This PR seems to include all of the commits from #6 and a few more

2022-09-30 08:42 UTC, merged